src/Entity/Blog.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
#[HasLifecycleCallbacks()]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255)]
    private $author;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\PrePersist]
    public function prePersist(){
        if(!isset($this->created_at)){
            $this->created_at = new \DateTime('now', new \DateTimeZone('Europe/Paris'));}
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Service\Pagination;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BlogController extends AbstractController
{
    //liste d'article avec pagination
    #[Route('/blog/{page<\d+>?1}', name: 'homeBlog')]
    public function index(Pagination $paginationService, $page): Response
    {
        $paginationService->setEntityClass(Blog::class)
                            ->setPage($page)
                            ->setLimit(10)
        ;

        return $this->render('blog/index.html.twig', [
            'title'=>'Restaurant Shangrila | Blog', 'pagination'=>$paginationService
        ]);
    }

    //detail de l'article
    #[Route('blog/show/{id}', name:'blog_show')]
    public function show(Blog $blog):Response{

        return $this->render('blog/show.html.twig', [
            'title'=>'Restaurant Shangrila | Détail de l\'article', 'blog'=>$blog
        ]);
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
{% include 'inc/nav-header.html.twig' %}
   
    <section class="container-fluid homeBlog">
    {% include './inc/flashs.html.twig' %}
     
        <div class="row justify-content-center">
          
            <div class="col-md-10 jumbotron">
                <h1 class="h2 mb-4">Blog</h1>
                <hr class="brown">
                <div class="row">

                {% for blog in pagination.data %}
                 <article class="col-4">
                    <div class="card">
                        <img src="{{blog.image}}" class="card-img-top" alt="{{blog.title}}">
                        <div class="card-body">
                        <h5 class="card-title">{{blog.title}}</h5>
                        <small><p class="card-text">{{blog.createdAt|date("d-m-Y H:i")}} par {{blog.author}}</p></small>
                        <p class="card-text">{{blog.content|u.truncate(100, '...', false)}}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                        <small><a href="{{path('blog_show', {'id':blog.id})}}" class="stretched-link">+ Détails</a></small>
                        </div>
                </article>

                {% endfor %}
                </div>
            </div>            
    </div>
    
    </section>

{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
{% include 'inc/nav-header.html.twig' %}
   
    <section class="container-fluid showBlog">
    {% include './inc/flashs.html.twig' %}
     
        <div class="row justify-content-center">
          
            <div class="col-md-10 jumbotron">
                <h1 class="h2 mb-1">{{blog.title}}</h1>
                <p class="card-text">Edité le {{blog.createdAt|date("d-m-Y")}} à {{blog.createdAt|date("H:i")}} par {{blog.author}}</p>
                 <article>
                    <div class="text-center d-flex blogContent">
                        <div class="col-md-6">
                            <img src="{{blog.image}}" class="card-img-top" alt="{{blog.title}}">
                        </div>
                        <div class="flex-column justify-content-around align-items-center">      
                                <p class="card-text pt-4 px-4 text-start">{{blog.content|raw}}</p>
                 
                                <a href="{{path('homeBlog')}}" class="btn btn-brown mb-3">Retour</a>
                        </div>
                        
                        
                </article>
                </div>
            </div>            
    </div>
    
    </section>

{% endblock %}